#!/usr/bin/env bash
set -e
set -x

source /common.sh

# Install packages
apt-get update
apt-get install -y iw hostapd dnsmasq lighttpd chromium-browser fbi

apt-get install -y --no-install-recommends \
  chromium-browser \
  xserver-xorg \
  xinit \
  x11-xserver-utils


# Enable CGI (optional if serving shell scripts with lighttpd)
lighty-enable-mod cgi || true

# Unpack filesystem (this populates /etc/systemd/system/, /var/www/html/, etc.)
unpack /filesystem/etc /etc
unpack /filesystem/usr /usr
unpack /filesystem/var /var
unpack /filesystem/boot /boot
unpack /filesystem/home /home

apt-get install -y fbi
echo "disable_splash=1" >> /boot/config.txt
sed -i 's/$/ logo.nologo consoleblank=0 loglevel=0 quiet/' /boot/cmdline.txt
systemctl enable splashscreen.service

# Now that files exist, we can modify them
chmod +x /var/www/html/wifi-submit.sh
chmod +x /usr/local/bin/start_hotspot_if_needed.sh
chmod +x /home/pi/.xinitrc

systemctl enable hostapd.service
systemctl enable dnsmasq.service
systemctl enable lighttpd.service
systemctl enable kiosk.service

ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

sed -i 's/^XKBLAYOUT=.*/XKBLAYOUT="us"/' /etc/default/keyboard
setupcon -k --save-only
