#!/usr/bin/env bash
set -e
set -x

source /common.sh

# Install necessary packages
apt-get update
apt-get install -y iw hostapd dnsmasq lighttpd

# Enable CGI if using lighttpd to serve shell script forms
lighty-enable-mod cgi

# === Unpack filesystem/ now ===
unpack /filesystem/root /

# Now you can safely chmod your web form handler
chmod +x /var/www/html/wifi-submit.sh

# And now systemd will find and enable the service unit
systemctl enable wifi-check.service
