#!/bin/bash
set -ex
source /common.sh
install_cleanup_trap

# Run Balena-provided WiFi Connect installer
bash <(curl -L https://github.com/balena-io/wifi-connect/raw/master/scripts/raspbian-install.sh)

systemctl_if_exists enable wifi-connect.service
